baseURL = "https://docs.vectorcharts.com/"
languageCode = "en-us"
title = "VectorCharts Documentation"
theme = "docs-theme"
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
    version = "v0.1.0"
    siteUrl = "http://localhost:1313"
    docsUrl = "http://localhost:1313"
    filesUrl = "http://localhost:1313"

[module]
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source = "static"
        target = "static"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "archetypes"
        target = "archetypes"

[menu]
    [[menu.main]]
        identifier = "getting_started"
        title = "Getting Started"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1
    [[menu.main]]
        identifier = "api_reference"
        title = "Core API"
        pre = "<span class='bp3-icon bp3-icon-code'></span>"
        weight = 2
    [[menu.main]]
        identifier = "chart_api_reference"
        title = "Chart API"
        pre = "<span class='bp3-icon bp3-icon-map'></span>"
        weight = 3
    [[menu.main]]
        identifier = "examples"
        title = "Examples"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 4
    [[menu.main]]
        identifier = "resources"
        title = "Resources"
        pre = "<span class='bp3-icon bp3-icon-document'></span>"
        weight = 5
    [[menu.oem]]
        identifier = "getting_started"
        title = "Getting Started"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1
    [[menu.oem]]
        identifier = "portal_api_reference"
        title = "Admin API"
        pre = "<span class='bp3-icon bp3-icon-code'></span>"
        weight = 2
    [[menu.oem]]
        identifier = "api_reference"
        title = "Core API"
        pre = "<span class='bp3-icon bp3-icon-code'></span>"
        weight = 3
    [[menu.oem]]
        identifier = "examples"
        title = "Examples"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 4
    [[menu.oem]]
        identifier = "resources"
        title = "Resources"
        pre = "<span class='bp3-icon bp3-icon-document'></span>"
        weight = 5
    [[menu.main]]
        identifier = "symbol_browser"
        parent = "resources"
        name = "Symbol Browser"
        title = "Symbol Browser"
        url = "https://symbology-docs.vectorcharts.com/"
        weight = 3
        post = "<span class='bp3-icon bp3-icon-share sidebarExternalIcon' aria-hidden='true'></span>"
    [[menu.main]]
        identifier = "status"
        parent = "resources"
        name = "Status"
        title = "Status"
        url = "https://status.vectorcharts.com/"
        weight = 4
        post = "<span class='bp3-icon bp3-icon-share sidebarExternalIcon' aria-hidden='true'></span>"
    [[menu.oem]]
        identifier = "symbol_browser"
        parent = "resources"
        name = "Symbol Browser"
        title = "Symbol Browser"
        url = "https://symbology-docs.vectorcharts.com/"
        weight = 3
        post = "<span class='bp3-icon bp3-icon-share sidebarExternalIcon' aria-hidden='true'></span>"
    [[menu.crowdsourced]]
        identifier = "status"
        parent = "resources"
        name = "Status"
        title = "Status"
        url = "https://status.vectorcharts.com/"
        weight = 1
        post = "<span class='bp3-icon bp3-icon-share sidebarExternalIcon' aria-hidden='true'></span>"
    [[menu.crowdsourced]]
        identifier = "getting_started"
        title = "Getting Started"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1
    [[menu.crowdsourced]]
        identifier = "hazard_report_api"
        title = "Hazard API"
        pre = "<span class='bp3-icon bp3-icon-warning-sign'></span>"
        weight = 2
    [[menu.crowdsourced]]
        identifier = "bathymetry_report_api"
        title = "Bathymetry API"
        pre = "<span class='bp3-icon bp3-icon-tint'></span>"
        weight = 3
    [[menu.crowdsourced]]
        identifier = "resources"
        title = "Resources"
        pre = "<span class='bp3-icon bp3-icon-document'></span>"
        weight = 4
    [[menu.crowdsourced]]
        identifier = "cs_overview"
        parent = "getting_started"
        name = "Overview"
        title = "Overview"
        url = "/crowdsourced/"
        weight = 1
    [[menu.crowdsourced]]
        identifier = "cs_authentication"
        parent = "getting_started"
        name = "Authentication"
        title = "Authentication"
        url = "/crowdsourced/authentication/"
        weight = 2
    [[menu.crowdsourced]]
        identifier = "ur_create"
        parent = "hazard_report_api"
        name = "Create Report"
        title = "Create Report"
        url = "/crowdsourced/create/"
        weight = 1
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-primary\">POST</div>"
    [[menu.crowdsourced]]
        identifier = "ur_vote"
        parent = "hazard_report_api"
        name = "Vote on Report"
        title = "Vote on Report"
        url = "/crowdsourced/vote/"
        weight = 2
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-primary\">POST</div>"
    [[menu.crowdsourced]]
        identifier = "ur_delete"
        parent = "hazard_report_api"
        name = "Delete Report"
        title = "Delete Report"
        url = "/crowdsourced/delete/"
        weight = 3
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-warning\">DELETE</div>"
    [[menu.crowdsourced]]
        identifier = "ur_list"
        parent = "hazard_report_api"
        name = "List Reports"
        title = "List Reports"
        url = "/crowdsourced/list/"
        weight = 4
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-success\">GET</div>"
    [[menu.crowdsourced]]
        identifier = "ur_mvt"
        parent = "hazard_report_api"
        name = "Get Reports (MVT)"
        title = "Get Reports (MVT)"
        url = "/crowdsourced/tile-mvt/"
        weight = 5
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-success\">GET</div>"
    [[menu.crowdsourced]]
        identifier = "ur_geojson"
        parent = "hazard_report_api"
        name = "Get Reports (GeoJSON)"
        title = "Get Reports (GeoJSON)"
        url = "/crowdsourced/tile-geojson/"
        weight = 6
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-success\">GET</div>"
    [[menu.crowdsourced]]
        identifier = "ur_create_bathymetry"
        parent = "bathymetry_report_api"
        name = "Upload Bathymetry"
        title = "Upload Bathymetry"
        url = "/crowdsourced/create-bathymetry/"
        weight = 1
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-primary\">POST</div>"
    [[menu.crowdsourced]]
        identifier = "ur_list_bathymetry"
        parent = "bathymetry_report_api"
        name = "Get Bathymetry Tracks"
        title = "Get Bathymetry Tracks"
        url = "/crowdsourced/list-bathymetry/"
        weight = 2
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-success\">GET</div>"
    [[menu.crowdsourced]]
        identifier = "ur_get_bathymetry"
        parent = "bathymetry_report_api"
        name = "Get Bathymetry Track"
        title = "Get Bathymetry Track"
        url = "/crowdsourced/get-bathymetry/"
        weight = 3
        pre = "<div class=\"bp3-tag bp3-minimal bp3-intent-success\">GET</div>"
