steps:
  - wait: ~
  - label: "build-hugo-docs"
    key: "build-hugo-docs"
    commands:
      - "hugo --minify --verbose"
    agents:
      queue: "self-hosted-linux-x86-64"
    artifact_paths:
      - "public/**/*"
  - wait: ~
  - label: "deploy-hugo-docs"
    key: "deploy-hugo-docs"
    commands:
      - rm -rf public/
      - mkdir -p public/
      - buildkite-agent artifact download 'public/**' public/
      - trifold status -v
      - trifold publish
    agents:
      queue: "self-hosted-linux-x86-64"
    branches: "main"

secrets:
  - BUNNY_API_KEY
